services:
  app:
    build:
      context: ./
      target: build
    environment:
      DB_HOST: "db"
      OTEL_SERVICE_NAME: "kotlin-example-app"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
      OTEL_LOGS_EXPORTER: "none"
      OTEL_METRICS_EXPORTER: "none"
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace
    command: ["java", "-javaagent:/workspace/build/container/opentelemetry-javaagent.jar", "-jar", "/workspace/build/libs/ktor-graphql-dataloader-with-otel-investigation-all.jar"]
    depends_on:
      - collector
      - db
  collector:
    image: otel/opentelemetry-collector-contrib:0.141.0@sha256:b14234c4bc1b7364629af272e564913bb57bdc9736d45b8b6db5ab3417dc75f9
    volumes:
      - ./collector-config.yaml:/collector-config.yaml
    command: ["--config=/collector-config.yaml"]
    depends_on:
      - jaeger
    ports:
      - "4318:4318"
  jaeger:
    image: jaegertracing/jaeger:2.17.0@sha256:6266573208d665ce5c17483bce0a75d0806480d92c84766d288d0aee885ce708
    ports:
      - "16686:16686"
  db:
    image: postgres:18.3@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
